FROM python:alpine

WORKDIR "/var/app"

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN pip install -e .

ENV FLASK_APP flaskr

ENV FLASK_ENV development

CMD ["flask", "run", "--host=0.0.0.0"]